---
- name: Check whether ChromeDriver is installed
  ansible.builtin.command: chromedriver --version
  register: chromedriver_installed
  changed_when: false
  ignore_errors: true
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"

- name: Install required packages
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
  loop:
    - fontconfig
    - GConf2
    - libX11
    - nss-tools
    - unzip
    - wget
  when: chromedriver_installed is failed

- name: Get latest version of ChromeDriver stable
  ansible.builtin.shell: |
    echo $(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
  register: driver_version
  changed_when: false
  failed_when: driver_version.stdout | length == 0
  when: chromedriver_installed is failed

- name: Install ChromeDriver
  ansible.builtin.unarchive:
    src:
      "https://chromedriver.storage.googleapis.com/{{ driver_version.stdout }}/chromedriver_linux64.zip"
    dest: /usr/local/bin
    remote_src: yes
    owner: root
    group: root
    mode: 0755
  when: chromedriver_installed is failed
