---
- name: Verify
  hosts: all

  tasks:
    - name: Check whether ChromeDriver is installed
      ansible.builtin.command: chromedriver --version
      register: CHROMEDRIVER_INSTALLED
      changed_when: false
      ignore_errors: True

    - name: Check OS version
      ansible.builtin.command: cat /etc/redhat-release
      register: OS_VERSION
      changed_when: false

    - name: Make sure ChromeDriver is installed
      ansible.builtin.debug:
        var: CHROMEDRIVER_INSTALLED

    - name: Show OS version
      ansible.builtin.debug:
        var: OS_VERSION
